//=====================================================
// This file was auto-generated by xlate_vreg v1.1
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    RTL_MAJOR
// Size:        32-bits
// Description: "major" portion of RTL revision "major.minor.build"
//
#define RTL_MAJOR                                                    0x0000000000000000ULL


//
// Register:    RTL_MINOR
// Size:        32-bits
// Description: "minor" portion of RTL revision "major.minor.build"
//
#define RTL_MINOR                                                    0x0000000000000004ULL


//
// Register:    RTL_BUILD
// Size:        32-bits
// Description: "build" portion of RTL revision "major.minor.build"
//
#define RTL_BUILD                                                    0x0000000000000008ULL


//
// Register:    RTL_DATE
// Size:        32-bits
// Description: Build date
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     month                          8   31:24 RO   N/A         Build month (1 thru 12)
//     day                            8   23:16 RO   N/A         Build date  (1 thru 31)
//     year                           16  15:00 RO   N/A         Build year  (4 digit year)
//
#define RTL_DATE                                                     0x0000000000000010ULL
#define RTL_DATE_month                                               0x0818000000000010ULL
#define RTL_DATE_day                                                 0x0810000000000010ULL
#define RTL_DATE_year                                                0x1000000000000010ULL


//
// Register:    RTL_TYPE
// Size:        32-bits
// Description: Uniquely identifies this RTL design
//
#define RTL_TYPE                                                     0x0000000000000014ULL


//
// Register:    RTL_TIME
// Size:        32-bits
// Description: Build date
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     hour                           8   23:16 RO   N/A         Build month (0 thru 23)
//     min                            8   15:08 RO   N/A         Build date  (0 thru 59)
//     sec                            8   07:00 RO   N/A         Build year  (0 thru 59)
//
#define RTL_TIME                                                     0x000000000000001cULL
#define RTL_TIME_hour                                                0x081000000000001cULL
#define RTL_TIME_min                                                 0x080800000000001cULL
#define RTL_TIME_sec                                                 0x080000000000001cULL


//
// Register:    RTL_GIT_HASH
// Size:        This is an array of five consecutive 32-bit registers
// Description: Git commit hash
//
#define RTL_GIT_HASH                                                 0x0000000000000040ULL


//
// Register:    REG_RESET
// Size:        32-bits
// Description: Write a 1 to this register to clear the counters
//
#define REG_RESET                                                    0x0000000000001000ULL


//
// Register:    REG_LINK_STAT
// Size:        32-bits
// Description: Reports the Ethernet "link-status" of the QSFP ports
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     ch0                            1       0 RO   N/A         QSFP_0 link status
//     ch1                            1       1 RO   N/A         QSFP_1 link status
//
#define REG_LINK_STAT                                                0x0000000000001004ULL
#define REG_LINK_STAT_ch0                                            0x0100000000001004ULL
#define REG_LINK_STAT_ch1                                            0x0101000000001004ULL


//
// Register:    REG_PORT_0
// Size:        32-bits
// Description: Port number of the sender's QSFP port
//
#define REG_PORT_0                                                   0x0000000000001100ULL


//
// Register:    REG_XMIT_START_0
// Size:        32-bits
// Description: Write a 1 to this register to send an ABM
//
#define REG_XMIT_START_0                                             0x0000000000001104ULL


//
// Register:    REG_FD_COUNT_0
// Size:        64-bits
// Description: Count of frame-data packets received
//
#define REG_FD_COUNT_0                                               0x0000000000001108ULL


//
// Register:    REG_MD_COUNT_0
// Size:        64-bits
// Description: Count of meta-data packets received
//
#define REG_MD_COUNT_0                                               0x0000000000001110ULL


//
// Register:    REG_FC_COUNT_0
// Size:        64-bits
// Description: Count of frame-counter packets received
//
#define REG_FC_COUNT_0                                               0x0000000000001118ULL


//
// Register:    REG_OTH_COUNT_0
// Size:        64-bits
// Description: Count of "other-sized" packets received
//
#define REG_OTH_COUNT_0                                              0x0000000000001120ULL


//
// Register:    REG_BAD_COUNT_0
// Size:        64-bits
// Description: Count of corrupted packets received
//
#define REG_BAD_COUNT_0                                              0x0000000000001128ULL


//
// Register:    REG_XMIT_SRC_0
// Size:        64-bits
// Description: Source address in host RAM of an ABM to send
//
#define REG_XMIT_SRC_0                                               0x0000000000001130ULL


//
// Register:    REG_PORT_1
// Size:        32-bits
// Description: Port number of the sender's QSFP port
//
#define REG_PORT_1                                                   0x0000000000001200ULL


//
// Register:    REG_XMIT_START_1
// Size:        32-bits
// Description: Write a 1 to this register to send an ABM
//
#define REG_XMIT_START_1                                             0x0000000000001204ULL


//
// Register:    REG_FD_COUNT_1
// Size:        64-bits
// Description: Count of frame-data packets received
//
#define REG_FD_COUNT_1                                               0x0000000000001208ULL


//
// Register:    REG_MD_COUNT_1
// Size:        64-bits
// Description: Count of meta-data packets received
//
#define REG_MD_COUNT_1                                               0x0000000000001210ULL


//
// Register:    REG_FC_COUNT_1
// Size:        64-bits
// Description: Count of frame-counter packets received
//
#define REG_FC_COUNT_1                                               0x0000000000001218ULL


//
// Register:    REG_OTH_COUNT_1
// Size:        64-bits
// Description: Count of "other-sized" packets received
//
#define REG_OTH_COUNT_1                                              0x0000000000001220ULL


//
// Register:    REG_BAD_COUNT_1
// Size:        64-bits
// Description: Count of corrupted packets received
//
#define REG_BAD_COUNT_1                                              0x0000000000001228ULL


//
// Register:    REG_XMIT_SRC_1
// Size:        64-bits
// Description: Source address in host RAM of an ABM to send
//
#define REG_XMIT_SRC_1                                               0x0000000000001230ULL



#endif
